### ISSUE TITLE
Unable to startProxy in Playwright global setup 

### ISSUE THREAD

**Issue by matthewlilley** [wevm/anvil.js#36]
Playwright imports CJS by default in global setup, but it will complain about get-port needing to be dyanmically imported. I made a patch in our repository: https://github.com/sushiswap/sushiswap/blob/master/patches/%40viem__anvil%400.0.6.patch

**Comment by matthewlilley** [comment]
Added here to track @fubhy

**Comment by matthewlilley** [comment]
@fubhy I forgot to mention, after looking over get-port it seems that a mutex is needed or else there's a chance the same port can be assigned to the different process.

https://github.com/sindresorhus/get-port#beware

**Comment by fubhy** [comment]
Thanks for the fix and sorry for the delay
